version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: thien_tam_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: buddhist_readings
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - thien_tam_network

  # Uncomment to run backend in Docker as well
  # backend:
  #   build: ./backend_thien_tam_app
  #   container_name: thien_tam_backend
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - PORT=4000
  #     - MONGO_URI=mongodb://mongodb:27017/buddhist_readings
  #     - TZ=Asia/Ho_Chi_Minh
  #     - NODE_ENV=development
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - thien_tam_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  thien_tam_network:
    driver: bridge

