version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: thien-tam-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: thientam
    volumes:
      - mongodb_data:/data/db
      - ./backend_thien_tam_app/seed:/docker-entrypoint-initdb.d
    networks:
      - thien-tam-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend_thien_tam_app
      dockerfile: Dockerfile
    container_name: thien-tam-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/thientam?authSource=admin
      PORT: 4000
      JWT_SECRET: development-jwt-secret-change-in-production
      REFRESH_SECRET: development-refresh-secret-change-in-production
      # Add your API keys here or use .env file
      # ELEVENLABS_API_KEY: your-api-key
      # GOOGLE_GEMINI_API_KEY: your-api-key
      # CLOUDINARY_CLOUD_NAME: your-cloud-name
      # CLOUDINARY_API_KEY: your-api-key
      # CLOUDINARY_API_SECRET: your-api-secret
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - thien-tam-network
    volumes:
      - ./backend_thien_tam_app/src:/app/src
      - backend_node_modules:/app/node_modules
    command: npm run dev

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:latest
    container_name: thien-tam-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - thien-tam-network

volumes:
  mongodb_data:
    driver: local
  backend_node_modules:
    driver: local

networks:
  thien-tam-network:
    driver: bridge

